"""
Docs stage: README + CHANGELOG entry + design document (docs/DESIGN.md) + ADR files for the generated
project. Deliberately a TEMPLATE filled from state (not a creative-writing
prompt) so the documentation is accurate to what was actually built and
tested. docs/openapi.yaml was already written verbatim from the design.
"""
from __future__ import annotations

import datetime as dt
import re
from pathlib import Path

from sdlc_orchestrator.core import config
from sdlc_orchestrator.integrations import gitops
from sdlc_orchestrator.integrations.design_html import render_design_html
from sdlc_orchestrator.policy.java_scan import contract_endpoints
from sdlc_orchestrator.workflow.nodes.common import repo_path, set_task_status
from sdlc_orchestrator.integrations.repo_io import write_files
from sdlc_orchestrator.workflow.stage import stage
from sdlc_orchestrator.core.state import CommitRecord, dump


def _slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")[:60] or "decision"


def _next_adr_number(repo: Path) -> int:
    d = repo / "docs/adr"
    nums = [int(m.group(1)) for p in d.glob("*.md") if (m := re.match(r"(\d+)-", p.name))] if d.exists() else []
    return max(nums, default=0) + 1


def render_readme(state: dict) -> str:
    spec = state["requirement_spec"]
    design = state["design_doc"]
    strategy = (state.get("codegen_strategy") or "full")
    rows = "\n".join(f"| {m} | `{p}` |" for m, p in sorted(contract_endpoints(design["api_contract"]), key=lambda x: (x[1], x[0])))
    cfg = "\n".join(f"| `{k}` | `{v}` |" for k, v in (design.get("configuration") or {}).items())
    nfrs = "\n".join(f"- {n}" for n in spec.get("baseline_nfrs", []) + spec.get("non_functional_requirements", []))
    adrs = "\n".join(f"- {a.get('title')}" for a in design.get("adrs", []))
    degraded = ("\n> **Degraded build:** the full (Redis-backed) strategy failed twice, so the orchestrator fell back to the "
                "`simple` strategy (Postgres-only, synchronous analytics, in-memory rate limiter). See CHANGELOG.\n"
                if strategy == "simple" else "")
    return f"""# URL Shortener Service

{spec.get('problem_statement', '')}

Generated by the agentic SDLC orchestrator (run `{state['run_id']}`, strategy `{strategy}`).
{degraded}
## Stack
Java {config.java_version()} · Spring Boot 4 · PostgreSQL (Flyway) · Redis · Spring Security (API key) · Actuator · springdoc (OpenAPI + Swagger UI)

## Prerequisites

To **run** the service you only need Docker; the JDK is needed only to run the tests outside Docker.

| Need | Version | Check | Install |
|---|---|---|---|
| Docker (Desktop, or Engine + Compose v2), **running** | recent | `docker info` | macOS: `brew install --cask docker` · Windows: install [Docker Desktop](https://www.docker.com/products/docker-desktop/) with the WSL 2 backend |
| Free host port **8080** | | macOS/Linux: `lsof -i :8080` · Windows: `netstat -ano \\| findstr :8080` | stop whatever holds it |
| JDK **{config.java_version()}** (only for `./mvnw test`) | {config.java_version()} | `java -version` | macOS: `brew install --cask temurin@{config.java_version()}` · Windows: `winget install EclipseAdoptium.Temurin.{config.java_version()}.JDK` |

Docker pulls Postgres 16, Redis 7 and builds the app image itself, so no database or Maven install is required.

## Quick start

**1. Set the two required secrets** (use your own values; never commit them):

macOS / Linux (bash/zsh):
```bash
export DB_PASSWORD=devpass
export SHORTENER_API_KEY=my-secret-key
```
Windows (PowerShell):
```powershell
$env:DB_PASSWORD = "devpass"
$env:SHORTENER_API_KEY = "my-secret-key"
```

**2. Build and start the stack** (app on `:8080`, plus Postgres and Redis; the first build takes a few minutes):
```bash
docker compose up --build
```
It is ready when `http://localhost:8080/actuator/health` returns `{{"status":"UP"}}`.

**3. Try the API.** Easiest: open the Swagger UI at <http://localhost:8080/swagger-ui/index.html>, click **Authorize**,
enter your `SHORTENER_API_KEY`, then use **Try it out**. Or with curl (Windows: use `curl.exe`):
```bash
# create a short link (needs the API key)
curl -s -X POST localhost:8080/api/shorten -H "X-API-Key: my-secret-key" -H "Content-Type: application/json" \\
     -d '{{"url":"https://example.com/some/long/path"}}'
# follow it: expect 302 with Location: https://example.com/...
curl -i localhost:8080/<shortCode>
# click analytics (eventually consistent, allow ~5 s)
curl -s localhost:8080/api/analytics/<shortCode>
```
Windows PowerShell: put the JSON in a file (`body.json`) and use `curl.exe -d "@body.json"`, or use Swagger UI.

**4. Stop.** `Ctrl+C`, then `docker compose down` (add `-v` to also delete the database volume).

## Endpoints
| Method | Path |
|---|---|
{rows}

Full contract: [`docs/openapi.yaml`](docs/openapi.yaml). The live OpenAPI spec is at
`http://localhost:8080/v3/api-docs`. Mutating endpoints require the `X-API-Key` header.

## Test
```bash
./mvnw test        # Windows: mvnw.cmd test ; needs Docker (Testcontainers starts Postgres + Redis) and JDK {config.java_version()}
```

## Troubleshooting
| Symptom | Fix |
|---|---|
| `set DB_PASSWORD` / `set SHORTENER_API_KEY` error from compose | export the two variables from step 1 in the same terminal |
| `port is already allocated` on 8080 | stop the other process or container using 8080 |
| `docker compose build` fails with a Maven Central 5xx | transient network error: run it again |
| `401` from `POST /api/shorten` | missing/incorrect `X-API-Key` header (Swagger: click Authorize) |
| `release version {config.java_version()} not supported` when running tests | your JDK is older than {config.java_version()}; install it and fix `JAVA_HOME` |

## Configuration
| Property | Value |
|---|---|
{cfg}

## Non-functional requirements
{nfrs}

## Architecture decisions
{adrs}

See [`docs/DESIGN.md`](docs/DESIGN.md) (colourful HTML version: [`docs/DESIGN.html`](docs/DESIGN.html), with sequence diagrams, risks and trade-offs) for the full design document and `docs/adr/` for the decision records.
"""


def _impl(state: dict) -> dict:
    repo = repo_path(state)
    design = state["design_doc"]
    run_id = state["run_id"]
    stamp = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    files: dict[str, str] = {"README.md": render_readme(state)}

    if design.get("design_document"):
        files["docs/DESIGN.md"] = design["design_document"].rstrip("\n") + "\n"
        files["docs/DESIGN.html"] = render_design_html(design["design_document"])

    n = _next_adr_number(repo)
    for adr in design.get("adrs", []):
        title = adr.get("title") or adr.get("decision", "decision")
        files[f"docs/adr/{n:03d}-{_slug(title)}.md"] = (
            f"# ADR {n:03d}: {title}\n\n**Run:** {run_id}\n\n## Decision\n{adr.get('decision', '')}\n\n"
            f"## Rationale\n{adr.get('rationale', '')}\n\n## Alternatives considered\n{adr.get('alternatives_considered', '')}\n")
        n += 1

    tr = state.get("test_results", {})
    entry = (
        f"## {stamp} - run {run_id} ({state.get('mode')})\n"
        f"- Requirement: {state['raw_requirement']}\n"
        f"- Codegen strategy: {state.get('codegen_strategy') or 'full'}"
        f"{' (FALLBACK after repeated failures)' if state.get('codegen_strategy') == 'simple' else ''}\n"
        f"- Tests: {tr.get('tests')} run, {tr.get('failures', 0)} failures, {tr.get('errors', 0)} errors\n"
        f"- Plan version: {state.get('plan_version', 1)}; retries: {len(state.get('retries', []))}; replans: {len(state.get('replans', []))}\n"
    )
    changelog = repo / "CHANGELOG.md"
    existing = changelog.read_text() if changelog.exists() else "# Changelog\n"
    files["CHANGELOG.md"] = existing.rstrip("\n") + "\n\n" + entry

    written = write_files(repo, files)
    msg = f"task(write-docs): README, CHANGELOG, design doc, ADRs [run {run_id}]"
    sha = gitops.commit_paths(repo, written, msg)
    ws = dict(state["workspace"])
    ws["last_good_sha"] = sha
    return {
        "workspace": ws, "docs": {"files": written, "changelog_entry": entry},
        "commits": [dump(CommitRecord(task_id="write-docs", sha=sha, message=msg))],
        "tasks": set_task_status(state, ["docs"], "done"),
        "code_artifacts": {p: files[p] for p in written},
        "_detail": {"files": written},
    }


docs_node = stage("docs", actor="agent:docs")(_impl)
