"""
Docs stage: README + CHANGELOG entry + design document (docs/DESIGN.md) + ADR files for the generated
project. Deliberately a TEMPLATE filled from state (not a creative-writing
prompt) so the documentation is accurate to what was actually built and
tested. docs/openapi.yaml was already written verbatim from the design.
"""
from __future__ import annotations

import datetime as dt
import re
from pathlib import Path

from sdlc_orchestrator.core import config
from sdlc_orchestrator.integrations import gitops
from sdlc_orchestrator.integrations.design_html import render_design_html
from sdlc_orchestrator.policy.java_scan import contract_endpoints
from sdlc_orchestrator.workflow.nodes.common import repo_path, set_task_status
from sdlc_orchestrator.integrations.repo_io import write_files
from sdlc_orchestrator.workflow.stage import stage
from sdlc_orchestrator.core.state import CommitRecord, dump


def _slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")[:60] or "decision"


def _next_adr_number(repo: Path) -> int:
    d = repo / "docs/adr"
    nums = [int(m.group(1)) for p in d.glob("*.md") if (m := re.match(r"(\d+)-", p.name))] if d.exists() else []
    return max(nums, default=0) + 1


def render_readme(state: dict) -> str:
    spec = state["requirement_spec"]
    design = state["design_doc"]
    strategy = (state.get("codegen_strategy") or "full")
    rows = "\n".join(f"| {m} | `{p}` |" for m, p in sorted(contract_endpoints(design["api_contract"]), key=lambda x: (x[1], x[0])))
    cfg = "\n".join(f"| `{k}` | `{v}` |" for k, v in (design.get("configuration") or {}).items())
    nfrs = "\n".join(f"- {n}" for n in spec.get("baseline_nfrs", []) + spec.get("non_functional_requirements", []))
    adrs = "\n".join(f"- {a.get('title')}" for a in design.get("adrs", []))
    degraded = ("\n> **Degraded build:** the full (Redis-backed) strategy failed twice, so the orchestrator fell back to the "
                "`simple` strategy (Postgres-only, synchronous analytics, in-memory rate limiter). See CHANGELOG.\n"
                if strategy == "simple" else "")
    return f"""# URL Shortener Service

{spec.get('problem_statement', '')}

Generated by the agentic SDLC orchestrator (run `{state['run_id']}`, strategy `{strategy}`).
{degraded}
## Stack
Java {config.java_version()} · Spring Boot 4 · PostgreSQL (Flyway) · Redis · Spring Security (API key) · Actuator

## Endpoints
| Method | Path |
|---|---|
{rows}

Full contract: [`docs/openapi.yaml`](docs/openapi.yaml). Once running, the live OpenAPI spec is at
`http://localhost:8080/v3/api-docs` and the Swagger UI at `http://localhost:8080/swagger-ui/index.html`. Mutating endpoints require the `X-API-Key` header.

## Run
```bash
export SHORTENER_API_KEY=change-me   # never commit a real key
docker compose up --build
curl -X POST localhost:8080/api/shorten -H "X-API-Key: $SHORTENER_API_KEY" -H 'Content-Type: application/json' \\
     -d '{{"originalUrl":"https://example.com"}}'
```

## Test
```bash
./mvnw test        # needs Docker (Testcontainers starts Postgres + Redis)
```

## Configuration
| Property | Value |
|---|---|
{cfg}

## Non-functional requirements
{nfrs}

## Architecture decisions
{adrs}

See [`docs/DESIGN.md`](docs/DESIGN.md) (colourful HTML version: [`docs/DESIGN.html`](docs/DESIGN.html), with sequence diagrams, risks and trade-offs) for the full design document and `docs/adr/` for the decision records.
"""


def _impl(state: dict) -> dict:
    repo = repo_path(state)
    design = state["design_doc"]
    run_id = state["run_id"]
    stamp = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    files: dict[str, str] = {"README.md": render_readme(state)}

    if design.get("design_document"):
        files["docs/DESIGN.md"] = design["design_document"].rstrip("\n") + "\n"
        files["docs/DESIGN.html"] = render_design_html(design["design_document"])

    n = _next_adr_number(repo)
    for adr in design.get("adrs", []):
        title = adr.get("title") or adr.get("decision", "decision")
        files[f"docs/adr/{n:03d}-{_slug(title)}.md"] = (
            f"# ADR {n:03d}: {title}\n\n**Run:** {run_id}\n\n## Decision\n{adr.get('decision', '')}\n\n"
            f"## Rationale\n{adr.get('rationale', '')}\n\n## Alternatives considered\n{adr.get('alternatives_considered', '')}\n")
        n += 1

    tr = state.get("test_results", {})
    entry = (
        f"## {stamp} - run {run_id} ({state.get('mode')})\n"
        f"- Requirement: {state['raw_requirement']}\n"
        f"- Codegen strategy: {state.get('codegen_strategy') or 'full'}"
        f"{' (FALLBACK after repeated failures)' if state.get('codegen_strategy') == 'simple' else ''}\n"
        f"- Tests: {tr.get('tests')} run, {tr.get('failures', 0)} failures, {tr.get('errors', 0)} errors\n"
        f"- Plan version: {state.get('plan_version', 1)}; retries: {len(state.get('retries', []))}; replans: {len(state.get('replans', []))}\n"
    )
    changelog = repo / "CHANGELOG.md"
    existing = changelog.read_text() if changelog.exists() else "# Changelog\n"
    files["CHANGELOG.md"] = existing.rstrip("\n") + "\n\n" + entry

    written = write_files(repo, files)
    msg = f"task(write-docs): README, CHANGELOG, design doc, ADRs [run {run_id}]"
    sha = gitops.commit_paths(repo, written, msg)
    ws = dict(state["workspace"])
    ws["last_good_sha"] = sha
    return {
        "workspace": ws, "docs": {"files": written, "changelog_entry": entry},
        "commits": [dump(CommitRecord(task_id="write-docs", sha=sha, message=msg))],
        "tasks": set_task_status(state, ["docs"], "done"),
        "code_artifacts": {p: files[p] for p in written},
        "_detail": {"files": written},
    }


docs_node = stage("docs", actor="agent:docs")(_impl)
